### ISSUE TITLE
`UPath.rglob("*")` doesn't list root level content

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/lamindb-setup#311]
@Koncopd 

To reproduce:
<img width="484" alt="Screenshot 2023-03-01 at 19 55 02" src="https://user-images.githubusercontent.com/38218185/222164660-c83d8fc6-52bf-4976-bc6a-28037b9570ec.png">

**Comment by Koncopd** [comment]
This was fixed in upath.
