### ISSUE TITLE
Centralize SQLite instance locking

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb-setup#529]
@Koncopd, why is this not centralized/modularized within `update_local_sqlite_file()`?

https://github.com/laminlabs/lamindb-setup/blob/5c06ab60f70d3cc4036d39d6379955faf3eec583/lamindb_setup/_load_instance.py#L128-L146

**Comment by Koncopd** [comment]
Also the lock should probably be before the synchronization, not after. I will go through this and rework if it is the correct approach.
