### ISSUE TITLE
Unlock and lock in init

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lamindb-setup#531]
Unlock happens here https://github.com/laminlabs/lamindb-setup/blob/4fa35a4a370bd5f826816429a76d2a954ca50c88/lamindb_setup/_init_instance.py#L232
https://github.com/laminlabs/lamindb-setup/blob/4fa35a4a370bd5f826816429a76d2a954ca50c88/lamindb_setup/_init_instance.py#L203
And then immediately lock https://github.com/laminlabs/lamindb-setup/blob/4fa35a4a370bd5f826816429a76d2a954ca50c88/lamindb_setup/_init_instance.py#L205

This doesn't break anything but can lead to problems if some logic there changes. Also an unneeded request.

**Comment by falexwolf** [comment]
Thanks for spotting, Sergei!
