### ISSUE TITLE
Folder upload

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb-setup#694]
I have this folder:

<img width="750" alt="image" src="https://github.com/laminlabs/lamindb-setup/assets/16916678/52888172-7b3d-4836-9eef-0f1334932acb">

If I save it as an artifact, I get a lot of logging and it seems to upload objects one by one:

<img width="669" alt="image" src="https://github.com/laminlabs/lamindb-setup/assets/16916678/53bcc737-8cea-437b-87fb-08d4a43def36">

This isn't the case if I only passed the `.zarr` folder, in which case I don't get any logging but it seems to upload the folder as a whole.

**Comment by falexwolf** [comment]
However, timing-wise, it's similar. So, it might just be something in the logging.

**Comment by Koncopd** [comment]
Yes, we don't log zarr uploads, i will rework the progress bar for folders soon.

**Comment by Koncopd** [comment]
About the logging, it shows one by one upload indeed for some reason, but it seems they are still concurrent in batches.

**Comment by Koncopd** [comment]
Could you compare runtimes please
`UPath("s3://bucket/folder_destination").upload_from("folder_source", recursive=True)`
vs
```
destination = UPath("s3://bucket/folder_destination")
source = Path("folder_source")
files = (file for file in source.rglob("*") if file.is_file())
for file in files:
    (destination / file.relative_to(source)).upload_from(file)
```
to be sure
