### ISSUE TITLE
UPath should have bucket & key attributes

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb-setup#696]
We have this in a bunch of places. Nobody can remember it and it's very error prone

<img width="250" alt="image" src="https://github.com/laminlabs/lamindb-setup/assets/16916678/7f061335-adef-4280-baf5-305abd83102c">

I wish we could subclass UPath to add these as properties.

**Comment by Koncopd** [comment]
It should have now, we need to migrate to a new version of UPath.
https://github.com/laminlabs/lamindb/issues/1503

**Comment by Koncopd** [comment]
This is now in `upath`, `path.drive` gives a bucket.
