### ISSUE TITLE
Can't import lamindb-setup on python 3.9

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lamindb-setup#710]
due to https://github.com/laminlabs/lamindb-setup/blob/01b1a6864d98672127606fd746c72e841d84a32e/lamindb_setup/core/types.py#L7

**Comment by Koncopd** [comment]
@falexwolf why not just use `typing.Union` here?

**Comment by falexwolf** [comment]
Yes, that's how I fixed it in my current PR - I want the new annotations for aesthetics reasons. The docs are way too ugly otherwise.

But for a TypeAlias, if Sphinx is properly configured, we'd not see Union, I think.

**Comment by falexwolf** [comment]
But in fact it might also not work at all: https://laminlabs.slack.com/archives/C04A0RMA0SC/p1712218806650409?thread_ts=1712086065.426689&cid=C04A0RMA0SC

**Comment by falexwolf** [comment]
I'm running docs building within lamindb on Python 3.8 now. This should avoid this from happening again.
