### ISSUE TITLE
CI started to hang

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb-setup#747]
https://laminlabs.slack.com/archives/C04A0RMA0SC/p1715029957219169

I don't what happened but since today the CI starts hanging in instances.

Maybe it's related to not signing out of auth, I don't yet know. It's also a problem in lamindb.

<img width="1052" alt="image" src="https://github.com/laminlabs/lamindb-setup/assets/16916678/8525ffde-d557-4ce4-842e-ba3b513fdc3b">

**Comment by Koncopd** [comment]
Hm, what can it be. I A new release of some package related to the testing envs? I thought it could be `nbclient`, but no new releases recently. Also i saw hanging tests without any notebooks.
Not sure how even to start investigating this.

**Comment by falexwolf** [comment]
Didn't see any hanging today: https://github.com/laminlabs/lamindb-setup/pull/749

**Comment by falexwolf** [comment]
Seeing it very rarely again on main:

https://github.com/laminlabs/lamindb-setup/actions/runs/8966614401/job/24622502660

**Comment by falexwolf** [comment]
Also randomly in lamindb:
<img width="1713" alt="image" src="https://github.com/laminlabs/lamindb-setup/assets/16916678/0c8ef04d-4d7d-47d2-b522-852fd5ad8de9">

Almost always after the tests ran through. 🤔

**Comment by Koncopd** [comment]
Maybe a nox release?

**Comment by falexwolf** [comment]
Hits us less in lamindb-setup now, but quite a LOT in lamindb:
<img width="1708" alt="image" src="https://github.com/laminlabs/lamindb-setup/assets/16916678/f72c84b0-27ce-4c3d-a951-f84def8be0a4">
