### ISSUE TITLE
Priorities key error

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb-setup#752]
This occurs randomly sometimes:
<img width="1273" alt="image" src="https://github.com/laminlabs/lamindb-setup/assets/16916678/d7f008ef-7ecf-4a0c-999b-7b60d2ec9bf5">

https://github.com/laminlabs/lamindb-setup/actions/runs/8967263869/job/24624446925

**Comment by Koncopd** [comment]
This means that the priorities directory is deleted already when this piece is running. I suppose this happens when several CI testsings run at the same time.

**Comment by Koncopd** [comment]
@falexwolf i am pretty sure this happens because hub-cloud(prod) and hub-cloud(staging) run this notebook on the same bucket.
