### ISSUE TITLE
Queried for API key if JWT expires

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb-setup#855]
I'm getting this, @Koncopd 

<img width="483" alt="image" src="https://github.com/user-attachments/assets/2471608e-80f7-4841-9648-37d883bb455f">

Probably what one should do it is to automatically refresh the token rather than asking the user to call `lamin login`.

**Comment by Koncopd** [comment]
But maybe we need to update the message from renewal.

**Comment by falexwolf** [comment]
My main issue is that: Upon an expiring JWT and seeing the message "call lamin login", why should I have to go to lamin.ai/settings and manually copy and paste an API key just because the JWT expires? These two things shouldn't have anything to do with each other, should they?

**Comment by Koncopd** [comment]
No, no, it is enough to do `lamin login <handle>` for this (https://github.com/laminlabs/lamindb-setup/pull/853).
I will change the message to
`"... call lamin login <handle> to avoid this". `

**Comment by Koncopd** [comment]
https://github.com/laminlabs/lamindb-setup/commit/436db6e167df07a31bdc3e05aa4e6f4e75bb12b8

**Comment by falexwolf** [comment]
Thank you!
