### ISSUE TITLE
♻️ Remove `db` and `storage` args from `ln.connect` and `lamin load` to simplify the user interface

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamindb-setup#862]
This is way too messy.

<img width="752" alt="image" src="https://github.com/user-attachments/assets/80f20813-7a8b-4f7d-b3c7-a6d0c8775040">

**Comment by falexwolf** [comment]
@Koncopd, can you attack this next to prepare what will be my next ask? 

https://github.com/laminlabs/pfizer-lamin-usage/issues/25

**Comment by Koncopd** [comment]
yep

**Comment by falexwolf** [comment]
I'm pretty sure we can remove all logic from the code & test base related to these two arguments, which will hopefully simplify everything a little.

These arguments are historical and date back to times when things were much more manual.
