### ISSUE TITLE
Permission error when saving a new artifact on python-3.12

### ISSUE THREAD

**Issue by ap--** [laminlabs/lamindb-setup#868]
This is a bit of an edge case since it's I think unsupported as of now by being an issue on 3.12, but I'm reporting here, so that you're aware:

When the following conditions are met:
- installing `lamindb` on python3.12 (installation succeeds)
- and saving an artifact to an instance with remote storage

a permission error is raised.

```
lamin save myfile.txt --descriptio "My File!"
[...]
PermissionError
```

The reason this seems to happen, is that in the code path below, local_filepath becomes a remote path due to lamindb_setup relying on undefined behavior.

https://github.com/laminlabs/lamindb-setup/blob/bef6ce521b0192825e00960e296f4d290780ba53/lamindb_setup/core/_settings_storage.py#L393-L404

What happens is that in line 399, the following happens:

```
❯ python3.12 -m venv venv
❯ source venv/bin/activate
❯ pip install universal-pathlib==0.2.2
Looking in indexes: https://pypi.org/simple
Collecting universal-pathlib==0.2.2
  Using cached universal_pathlib-0.2.2-py3-none-any.whl.metadata (25 kB)
Collecting fsspec>=2022.1.0 (from universal-pathlib==0.2.2)
  Using cached fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Using cached universal_pathlib-0.2.2-py3-none-any.whl (46 kB)
Using cached fsspec-2024.9.0-py3-none-any.whl (179 kB)
Installing collected packages: fsspec, universal-pathlib
Successfully installed fsspec-2024.9.0 universal-pathlib-0.2.2

❯ python
Python 3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import upath
>>> fp = upath.UPath("s3://mybucket/.lamindb/abcdef123456")
>>> cd = upath.UPath("/some/local/path/lamin")
>>> cd / fp
S3Path('s3:///some/local/path/lamin/s3://mybucket/.lamindb/abcdef123456')
```

In `universal-pathlib>=0.2.5` this was fixed, and joining a remote path to an localpath as in `localpath / remotepath` raises a `ValueError` because the protocols don't match, and remote paths are all absolute.

The fact that `self.cache_dir / filepath` works for `type(cache_dir) == PosixUPath` and `type(filepath) == S3Path` is undefined behavior.

An easy fix if you don't want to upgrade the upath version for now would be to do: `self.cache_dir / filepath.path` to strip the protocol.

If there's interest, I can work on a minimally invasive PR ☺️ 

Cheers,
Andreas

**Comment by Koncopd** [comment]
Oh, thank you very much for noticing this. Indeed this seems easy to fix. You can make a PR or i can do it.

**Comment by Koncopd** [comment]
fixing now
