### ISSUE TITLE
`supabase==2.2.1` pin needed?

### ISSUE THREAD

**Issue by ap--** [laminlabs/lamindb-setup#908]
Hi Lamins,

is the supabase pin to `==2.2.1` required?

https://github.com/laminlabs/lamindb-setup/blob/eac5b9208c691f4ac7a54ba0d8541c97587235f9/pyproject.toml#L23

It turns out that that's the one version of supabase that's missing on conda-forge.

- https://github.com/conda-forge/supabase-feedstock
- https://anaconda.org/conda-forge/supabase/files

Cheers,
Andreas :smiley:

**Comment by ap--** [comment]
xref: https://github.com/conda-forge/supabase-feedstock/issues/57

**Comment by Koncopd** [comment]
fixed by https://github.com/laminlabs/lamindb-setup/pull/909
